---
title: ""
---

<style>
.column-left{
  float: left;
  width: 70%;
  text-align: left;
}
.column-right{
  display: inline-block;
  width: 30%;
  text-align: left;
}
.container{
  padding-left:4em;
}

</style>

```{r packages, echo = FALSE}
library(png)
library(knitr)
img <- readPNG("/home/dj-ubuntu/Pictures/theo.png", native = TRUE, info = TRUE)
```



<div class = "column-left">
<col width = "300">

<br><br><br>

Hi and welcome to my webpage!  My name is Darrel Robinson and I am a PhD Candidate at the Department of Government at Uppsala University, and I am also affiliated with the Uppsala Center for Labor Studies.  I conduct my research in two fields of political science: the first connects to the large literature which attempts to isolate the causal effect of education on political behavior and attitudes; the second studies the effect of policies that autocratic governments use to build support among the populace.  These two fields overlap in my thesis which investigates the conditional effect of education.  

<br> 

My studies all have a focus on causal inference which includes analyses based on policy reforms, matching designs, or experiments embedded within surveys.

<br> 

This is intended in part to be a research webpage where I present myself and my work, but also as a way to learn more R and store some of the projects that I've made while learning new techniques and code.  Check out the [Research](research.html) tab for the former and the [R Projects](r_stuff.html) tab for some of the latter.  

</div>




<div class = "column-right">

<br>
<br>
<br>


<div class = "container">

darrel.robinson@statsvet.uu.se

<a href="https://www.linkedin.com/in/darrel-robinson-25776436/" target="_blank">LinkedIn</a>

</div>
</div>
</div>

---





