---
title: "R Projects"
---

This page is just a various collection of things I've done in R that I thought were interesting or useful.  I've primarily done them for myself to learn a new technique or work with a new package, and I've uploaded them here to save and share them.  

<br>

## [Linear Regression with Optimization](reg_by_optimization.html)

Writing custom regression functions using R's built-in optimization function.  

---


## [Logistic regression 'by-hand' in R](logistic.html)

A short break down of logistic regression I wrote when I was learning the method.  

---

## [A simple trading algorithm and stock dashboard with RShiny](https://darrelrobinson.shinyapps.io/stock_dashboard/)

This is a very basic algorithm and dashboard I use to follow stocks.  The dashboard can be used to view and analyze trends whereas the "Buy" and "Sell" signals are based on RSI and Bollinger Band values.  The tool can be used for short-term trading or for timing entry points with long-term strategies.  Feel free to use it or copy and develop it further with your own strategies.  

The app is written with RShiny and the data is collected and visualized using the quantmod package.  The code can be found at my <a href="https://github.com/darrelrobinson" target="_blank">GitHub profile</a>.


---


## An RShiny app to explore some of the China General Social Survey

I use the CGSS in my dissertation but it's not a very accessible database.  1) it's only in Chinese so I am one of the few (the only that I know) non-Chinese scholars using it.  2) it doesn't have online analysis like other large survey projects so the only way to get an idea of what is in the dataset is to apply for access and start exploring (this is made more difficult because of point 1).  So, I am working on the first data explorer for (some of) the CGSS.  Coming soon.


---

## [A 3D visualization of how dummy variables shift the intercept in linear regression (for Methods C students)](dummy.html)

In the BA Research methods course at the Department of Government we introduce students to dummy variables in linear regression.  In class we demonstrate mathematically that dummy variables shift the intercept of the regression line by studying the regression line equation, but a visualization of why this is the case can be helpful so that students can see how this happens. In this project I use interactive 3D visualizations to demonstrate this concept.  

The figures are built with the rgl package, click <a href="https://cran.r-project.org/web/packages/rgl/vignettes/rgl.html" target="_blank">here</a> for the documentation.



---


## [Webscraping with R - Exploring popular baby names in Sweden](scraper.html)

Ever wondered how to scrape a webpage and analyze the data?  The internet is full of interesting data and I'm hoping to incorporate these kind of things into my research in the future.  In this post I use the Rvest package to scrape name data and visualize some trends.  



---


## [Personal webpage](https://github.com/darrelrobinson)

And of course, this webpage!  It's written in RMarkdown and hosted on GitHub. <a href="http://nickstrayer.me/RMarkdown_Sites_tutorial/" target="_blank">This</a> blog post and <a href="http://www.lucymcgowan.com/index.html" target="_blank">Lucy D'Agostino McGowan's</a> GitHub got me started so check them out if you're interested in creating a page yourself with RMarkdown.  Also, you can find my GitHub <a href="https://github.com/darrelrobinson" target="_blank">here</a> if you want to see what I've done.  




---




