---
title: "Research"
---
<br>

## Self-Censorship in Authoritarian States: Response bias in measures of popular support in China

#### With Marcus Tannenberg, University of Gothenburg

Abstract: The study of popular support for authoritarian regimes, and the comparative study of political
attitudes, has long relied on the assumption that survey respondents provide truthful answers on
surveys. However, when measuring regime support in closed political systems there is a distinct risk
that individuals are less than forthright due to fear that their opinions may be made known to the
public or the authorities. In order to test this assumption, we conducted a novel web-based survey
in China in which we included four list experiments of commonly used items in the comparative
literature on regime support. We find systematic bias for all four measures as a result of self-censorship;
substantially more individuals state that they support the regime with direct questioning
than do when presented with our anonymous, indirect list experiments. The level of self-censorship,
which ranges from 16 to 22 percentage points, is considerably higher than previously thought. Self-censorship
is further most prevalent among the wealthy, urban, female and younger respondents.
These findings indicate that prior studies that have found high levels of support for the Chinese
regime using these particular measures likely overestimate the true level of support. Further, cross-national
studies which compare popular support across regime type may be systematically biased if
responses are not subject to the same level of falsification across regime types.

Full working paper found <a href="https://www.v-dem.net/media/filer_public/2d/bc/2dbc44aa-5558-4972-9e01-f4ca144586a1/v-dem_working_paper_2018_66.pdf" target="_blank">here</a>.


---

## Education Opportunity and Support for Authoritarian Rule: Evidence from the expansion of higher education in China

Abstract: A vast modernization literature argues for the democratizing potential of education.  Yet authoritarian regimes throughout the world expand their education systems in an effort to appease citizens and promote economic growth.  Scholars of China argue that this strategy allows the regime to enjoy a high level of public support.  These two diverging theoretical predictions raise an interesting empirical question, what effect does education opportunity have on individual-level support for authoritarian rule?  I leverage an expansion in higher education in China as an identification strategy to study the effect of education opportunity on two measures of support for authoritarian rule: support for government censorship and trust in the central government.  While the reform opened  millions of positions in higher education, it has also resulted in high graduate unemployment and a general decrease in perceived quality.  I find that higher education opportunity led to a substantial decrease in regime support.  I further find that education opportunity led to increased belief that citizens should have an input on policy, and increased social trust.  I argue that this is evidence that value change in education is responsible for the negative effect of the education reform, not dissatisfaction due to high graduate unemployment.

Full working paper found at my <a href="https://www.researchgate.net/profile/Darrel_Robinson/contributions" target="_blank">ResearchGate</a> page.

---

## Limited Time or Secure Residence: A study of the short-term effect of permanent residency on labour market inclusion

#### With Kristoffer Jutvik, Uppsala University

Abstract: In this study we exploit a sudden policy change, implemented in Sweden, in order to evaluate the effects of permanent residency on labour market inclusion. In short, the policy change implied that Syrians were granted permanent instead of temporary residency as before the new regulations. Using detailed Swedish registry data, we examine the effect of the introduction of permanent residency on three measures of labour market inclusion 16 months after residency status was granted. We analyze the data through a simple difference-in-means as well as through comparison to groups unaffected by the policy in a difference-in-differences design and a synthetic control group approach. Our conclusions are twofold. On the one hand, we conclude that temporary residents that are subject to a relatively less-inclusive situation earn more and are unemployed less. However, at the same time, they are less likely to spend time in education than are those with permanent residency. While the political debate about the issue is often framed in such empirical terms, our results suggest that both approaches can be supported empirically, albeit with different metrics  of success.  In our view then, the issue should be viewed as largely normative.  Rather than debate whether one approach will lead to greater inclusion than the other, focus should be shifted to discussing the type of inclusion that the different approaches are likely to provide. 



---

## Education, Family Background, and Political Knowledge: Testing the proxy hypothesis with identical twins

Abstract: A robust, positive correlation between education and political knowledge is a well-known finding in political science. However, in recent years the interpretation of education as causally prior to political knowledge has been challenged. Specifically, proponents of the education-as-a-proxy hypothesis argue that factors related to family background confound the observed relationship thereby rendering such a correlation spurious. I test this hypothesis using matching identical twins and estimating the relationship between education and factual political knowledge with family fixed-effects. I find that family background confounds the general effect of education but that education has a positive effect on political knowledge for those from homes with low political discussion – education compensates for a lack of socialization in the home. Further, I argue that these results can be cautiously generalized beyond the twin sample through comparison to a nationally representative data set.

Full working paper found at my <a href="https://www.researchgate.net/publication/328943736_Education_Family_Background_and_Political_Knowledge_Testing_the_proxy_hypothesis_with_identical_twins">ResearchGate</a> page.
